### ISSUE TITLE
[Warning] Data loss when $BackupFolderPath is parent path of $Worldsavelocation 

### ISSUE THREAD

**Issue by bllngr** [Wdrussell1/Valheim-Backup-Script#2]
I configured the script to create the ZIPs in `%USERPROFILE%\AppData\LocalLow\IronGate\Valheim` so that I can unzip them directly when having to restore a backup.

Since `$BackupFolderPath` is pruned in [l. 86](https://github.com/Wdrussell1/Valheim-Backup-Script/blob/main/Valheim-Backup-Script.ps1#L86) of the script, it just deleted my screenshots and everything else that I had in this directory (except what is backed up), including itself.

This should probably be fixed in a way that it only removes stuff that matches the `$BackupName` pattern.

Thankfully, I had a backup of my backups.

**Comment by Wdrussell1** [comment]
Not sure I understand the problem here. 
$BackupFolderPath is set to be in the IronGate folder. This is intentionally NOT in the Valheim folder. As is the script works exactly as designed and only prunes backups as the script is run. If you made changes then unfortunately I cannot control that. 

Misuse of any script that deletes files is going to cause you issues.

**Comment by bllngr** [comment]
> $BackupFolderPath is set to be in the IronGate folder. This is intentionally NOT in the Valheim folder. 

Well, that's not obvious for the user of the script. It says `CONFIGURATION ITEMS` at the top, and them gives the option to configure the save data and backup path. Nowhere does it say that that everything within the backup folder path might be deleted. I don't see that as "misuse", if it's explicitly marked as configurable.

But then again, it's your script and you don't have to care. I just wanted to give other people a heads up so that they don't lose their saves as I did.
